sudo: required
services:
  - docker

before_install:
  - docker build -t beaglefoot/docker-kubernetes-udemy -f Dockerfile.dev .

script:
  - docker run beaglefoot/docker-kubernetes-udemy npm run test -- --coverage